language: node_js
node_js:
  - "8"
stages:
  # - name: build
  # Build the docker image only on master branch
  - name: deploy

branches:
  only:
    - master

cache: npm

before_install:
  - cd web

jobs:
  include:
    - stage: deploy
      script:
        - npm run build
      deploy:
        provider: pages
        skip-cleanup: true
        repo: hkvoteguide/hkvoteguide.github.io
        fqdn: vote4.hk
        github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep-history: true
        committer_from_gh: true
        target_branch: master
        local-dir: web/build # the local dir is relative to root and ignoring the one set with before_install
        on:
          branch: master